// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendorRiskScoreAPI.Data;

#nullable disable

namespace VendorRiskScoreAPI.Migrations
{
    [DbContext(typeof(VendorRiskScoreDbContext))]
    [Migration("20251126090207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VendorRiskScoreAPI.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ContractValid")
                        .HasColumnType("boolean");

                    b.Property<bool>("PentestReportValid")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrivacyPolicyValid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Document", (string)null);
                });

            modelBuilder.Entity("VendorRiskScoreAPI.Domain.Entities.RiskAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<float>("RiskScore")
                        .HasColumnType("real");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendorId")
                        .IsUnique();

                    b.ToTable("RiskAssessment", (string)null);
                });

            modelBuilder.Entity("VendorRiskScoreAPI.Domain.Entities.VendorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<int>("FinancialHealth")
                        .HasColumnType("integer");

                    b.Property<int>("MajorIncidents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SlaUpTime")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("VendorProfile", (string)null);
                });

            modelBuilder.Entity("VendorRiskScoreAPI.Domain.Entities.VendorSecurityCert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CertName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorSecurityCert", (string)null);
                });

            modelBuilder.Entity("VendorRiskScoreAPI.Domain.Entities.RiskAssessment", b =>
                {
                    b.HasOne("VendorRiskScoreAPI.Domain.Entities.VendorProfile", "VendorProfile")
                        .WithOne("RiskAssessment")
                        .HasForeignKey("VendorRiskScoreAPI.Domain.Entities.RiskAssessment", "VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorProfile");
                });

            modelBuilder.Entity("VendorRiskScoreAPI.Domain.Entities.VendorProfile", b =>
                {
                    b.HasOne("VendorRiskScoreAPI.Domain.Entities.Document", "Document")
                        .WithOne()
                        .HasForeignKey("VendorRiskScoreAPI.Domain.Entities.VendorProfile", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("VendorRiskScoreAPI.Domain.Entities.VendorSecurityCert", b =>
                {
                    b.HasOne("VendorRiskScoreAPI.Domain.Entities.VendorProfile", "VendorProfile")
                        .WithMany("SecurityCerts")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorProfile");
                });

            modelBuilder.Entity("VendorRiskScoreAPI.Domain.Entities.VendorProfile", b =>
                {
                    b.Navigation("RiskAssessment")
                        .IsRequired();

                    b.Navigation("SecurityCerts");
                });
#pragma warning restore 612, 618
        }
    }
}
